export const CART_ADD_REQUEST = 'CART_ADD_REQUEST'
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS'
export const CART_ADD_FAIL = 'CART_ADD_FAIL'

export const CART_REMOVE_REQUEST = 'CART_REMOVE_REQUEST'
export const CART_REMOVE_SUCCESS = 'CART_REMOVE_SUCCESS'
export const CART_REMOVE_FAIL = 'CART_REMOVE_FAIL'

export const CART_CLEAR = 'CART_CLEAR'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_SUCCESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
